### ISSUE TITLE
Apple's orignal implemention seems to support reuse the cgContext?

### ISSUE THREAD

**Issue by Josscii** [shaps80/GraphicsRenderer#4]
I dig into dumped ios runtime headers, and find that,
<img width="470" alt="default" src="https://cloud.githubusercontent.com/assets/6898115/26719664/f458552a-47b7-11e7-9fec-007acb8df10a.png">
I saw you codes, you seems to ignore these mechanism.
May it hurt perfomance? Do you have any idea about it?

**Comment by shaps80** [comment]
I didn't go into the same level of detail. Would be interested in a PR though if its something you want to do?

**Comment by Josscii** [comment]
I have no idea on how apple managed that and I may be not able to implement it as well, I'm just wonder that why apple did that, may be someone can figure it out.

**Comment by shaps80** [comment]
I don’t have time atm but I’ll try and take a better look at some point. I know they reuse things like the current context to improve performance. I guess it’s to reuse the same graphics context when you’re already using one. My blocks will always generate a new context since they really just wrap core graphics calls
